version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - customerchurmprediction-network

  customer-churm-prediction:
    image: customer-churm-prediction
    container_name: customer-churm-prediction
    build:
      context: .
    depends_on:
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - customerchurmprediction-network
    environment:
      - MONGO_URL=mongodb://localhost:27017

networks:
  customerchurmprediction-network:
    driver: bridge